version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "the-card-room"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hoa4cv2sc075"
s3_prefix = "the-card-room"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=TheCardRoomConnections"
